# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-11 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='No bio available', max_length=100),
        ),
    ]
