# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-10 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0005_auto_20190310_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='noir_image',
            new_name='image_path',
        ),
    ]
